spring:
  profiles:
    active: local

  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
#        show_sql: true
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: utf-8
      platform: h2
logging.level:
  org:
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
    springframework.jdbc: debug